# Generated by Django 4.2.3 on 2024-04-22 11:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PowerBIDetail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True)),
                ("ss_id", models.IntegerField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "access_role",
                    models.CharField(
                        choices=[
                            ("super_admin", "Super Admin"),
                            ("tenant_admin", "Tenant Admin"),
                            ("tenant_manager", "Tenant Manager"),
                            ("tenant_user", "Tenant User"),
                        ],
                        max_length=512,
                    ),
                ),
                ("report_id", models.CharField(max_length=512)),
                ("report_name", models.CharField(max_length=512)),
                ("embed_url", models.CharField(max_length=512)),
                ("dataset_id", models.CharField(max_length=512)),
                ("dataset_workspace_id", models.CharField(max_length=512)),
                ("web_url", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("data", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "default_related_name": "related_power_bi_details",
            },
        ),
    ]
