# Generated by Django 4.2.3 on 2023-11-30 07:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0014_remove_advancedlearningpath_credit_score_and_more"),
        ("meta", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="YakshaConfiguration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ("ss_id", models.IntegerField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("aeye_proctoring_config", models.TextField(blank=True, default=None, null=True)),
                ("attempt", models.PositiveIntegerField()),
                ("pass_percentage", models.PositiveIntegerField()),
                ("duration", models.PositiveIntegerField()),
                (
                    "result_type",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "Do not show results to candidate"),
                            (2, "Show detailed section and skill level score metrics to the candidate."),
                            (3, "Show only assessment level score metrics to the candidate."),
                            (4, "Redirect to the custom URL on submission of assessment."),
                        ]
                    ),
                ),
                ("negative_score_percentage", models.IntegerField(default=0)),
                ("window_violation_limit", models.IntegerField(default=0)),
                ("is_shuffling_enabled", models.BooleanField(default=False)),
                ("is_plagiarism_enabled", models.BooleanField(default=False)),
                ("is_proctoring_enabled", models.BooleanField(default=False)),
                ("is_full_screen_mode_enabled", models.BooleanField(default=False)),
                ("is_window_violation_restricted", models.BooleanField(default=False)),
                ("is_aeye_proctoring_enabled", models.BooleanField(default=False)),
                ("is_default", models.BooleanField()),
                (
                    "assignment",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.assignment",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.course",
                    ),
                ),
                (
                    "learning_path",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.learningpath",
                    ),
                ),
                (
                    "playground",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.playground",
                    ),
                ),
                (
                    "skill_traveller",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.skilltraveller",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "default_related_name": "related_yaksha_configurations",
            },
        ),
    ]
