# Generated by Django 4.2.3 on 2023-12-04 08:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0015_remove_assignment_allowed_submission_and_more"),
        ("meta", "0002_yakshaconfiguration"),
    ]

    operations = [
        migrations.RenameField(
            model_name="yakshaconfiguration",
            old_name="attempt",
            new_name="allowed_attempts",
        ),
        migrations.AddField(
            model_name="yakshaconfiguration",
            name="catalogue",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="learning.catalogue",
            ),
        ),
        migrations.AlterField(
            model_name="yakshaconfiguration",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="MMLConfiguration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ("ss_id", models.IntegerField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "submission_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("online_file_submission", "Online File Submission"),
                            ("on_paper_submission", "On Paper Submission"),
                            ("observed_in_person", "Observed In Person"),
                        ],
                        default=None,
                        max_length=512,
                        null=True,
                    ),
                ),
                (
                    "files_allowed",
                    models.CharField(
                        blank=True,
                        choices=[("single_file", "Single File"), ("multiple_file", "Multiple File")],
                        default=None,
                        max_length=512,
                        null=True,
                    ),
                ),
                (
                    "allowed_submission",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("all", "All submissions are allowed"),
                            ("one", "Only one submission allowed"),
                            ("recent", "Only the most recent submission is allowed"),
                        ],
                        default=None,
                        max_length=512,
                        null=True,
                    ),
                ),
                ("extensions_allowed", models.TextField(blank=True, default=None, null=True)),
                ("allowed_attempts", models.PositiveIntegerField()),
                ("max_files_allowed", models.IntegerField(default=1)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "assignment",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.assignment",
                    ),
                ),
                (
                    "catalogue",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.catalogue",
                    ),
                ),
                (
                    "playground",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.playground",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "default_related_name": "related_mml_configurations",
            },
        ),
    ]
