# Generated by Django 4.2.3 on 2023-12-08 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0019_alter_courseassessment_options_and_more"),
        ("meta", "0004_alter_faculty_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="mmlconfiguration",
            name="course",
            field=models.ForeignKey(
                blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to="learning.course"
            ),
        ),
        migrations.AddField(
            model_name="mmlconfiguration",
            name="learning_path",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="learning.learningpath",
            ),
        ),
        migrations.AddField(
            model_name="mmlconfiguration",
            name="pass_percentage",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="mmlconfiguration",
            name="skill_traveller",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="learning.skilltraveller",
            ),
        ),
        migrations.AlterField(
            model_name="yakshaconfiguration",
            name="pass_percentage",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
