# Generated by Django 4.2.3 on 2023-12-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meta", "0005_mmlconfiguration_course_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="yakshaconfiguration",
            name="is_practice",
            field=models.BooleanField(default=False),
        ),
    ]
