# Generated by Django 4.2.3 on 2023-12-14 08:12

import apps.common.model_fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("meta", "0006_yakshaconfiguration_is_practice"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ("ss_id", models.IntegerField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=512, unique=True)),
                ("email", models.EmailField(blank=True, default=None, max_length=254, null=True)),
                (
                    "contact_number",
                    apps.common.model_fields.AppPhoneNumberField(
                        blank=True, default=None, max_length=128, null=True, region=None
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "default_related_name": "related_vendors",
            },
        ),
    ]
