# Generated by Django 4.2.3 on 2023-12-26 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0028_alter_advancedlearningpathresource_custom_url_and_more"),
        ("meta", "0008_feedbacktemplate_feedbacktemplatequestion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mmlconfiguration",
            name="alp",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="learning.advancedlearningpath",
            ),
        ),
        migrations.AddField(
            model_name="yakshaconfiguration",
            name="alp",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="learning.advancedlearningpath",
            ),
        ),
    ]
