# Generated by Django 4.2.3 on 2024-03-14 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0043_catalogue_ccms_assignment_group_and_more"),
        ("meta", "0012_alter_facultyimagemodel_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="mmlconfiguration",
            name="assignment_group",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="learning.assignmentgroup",
            ),
        ),
        migrations.AddField(
            model_name="yakshaconfiguration",
            name="assignment_group",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="learning.assignmentgroup",
            ),
        ),
    ]
