# Generated by Django 4.2.3 on 2024-05-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0013_mmlconfiguration_assignment_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=512),
        ),
    ]
