# Generated by Django 4.2.3 on 2023-12-11 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("virtutor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledsession",
            name="creator_role",
            field=models.CharField(
                blank=True,
                choices=[("admin", "Admin"), ("manager", "Manager"), ("learner", "Learner"), ("author", "Author")],
                default=None,
                max_length=512,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="scheduledsession",
            name="recording_days",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="scheduledsession",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_user_scheduled_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="scheduledsession",
            name="base_url",
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="scheduledsession",
            name="external_session_url",
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="scheduledsession",
            name="session_title",
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
    ]
