# Generated by Django 4.2.3 on 2023-11-06 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarActivity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ("ss_id", models.IntegerField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=512)),
                (
                    "activity_type",
                    models.CharField(choices=[("event", "Event"), ("focus_time", "Focus Time")], max_length=512),
                ),
                (
                    "repeat_type",
                    models.CharField(
                        choices=[
                            ("does_not_repeat", "Does not repeat"),
                            ("daily", "Daily"),
                            ("every_weekday", "Every Weekday (Monday to Friday)"),
                            ("custom", "Custom"),
                        ],
                        default="does_not_repeat",
                        max_length=512,
                    ),
                ),
                (
                    "repeat_every_type",
                    models.CharField(
                        blank=True,
                        choices=[("day", "Day"), ("week", "Week"), ("month", "Month"), ("year", "Year")],
                        default=None,
                        max_length=512,
                        null=True,
                    ),
                ),
                (
                    "ends_type",
                    models.CharField(
                        blank=True,
                        choices=[("never", "Never"), ("on", "On"), ("after", "After")],
                        default=None,
                        max_length=512,
                        null=True,
                    ),
                ),
                (
                    "user_status",
                    models.CharField(choices=[("busy", "Busy"), ("free", "Free")], default="busy", max_length=512),
                ),
                (
                    "user_visibility",
                    models.CharField(
                        choices=[
                            ("default_visibility", "Default Visibility"),
                            ("public", "Public"),
                            ("private", "Private"),
                        ],
                        default="default_visibility",
                        max_length=512,
                    ),
                ),
                (
                    "notify",
                    models.IntegerField(
                        choices=[
                            (5, "5 minutes before"),
                            (10, "10 minutes before"),
                            (15, "15 minutes before"),
                            (30, "30 minutes before"),
                            (60, "1 hour before"),
                            (1440, "1 day before"),
                        ],
                        default=30,
                    ),
                ),
                ("repeat_on", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("description", models.TextField(blank=True, default=None, null=True)),
                ("repeat_occurrence_no", models.PositiveIntegerField(blank=True, default=None, null=True)),
                ("ends_after", models.PositiveIntegerField(blank=True, default=None, null=True)),
                ("is_auto_decline", models.BooleanField(default=False)),
                ("activity_date", models.DateField()),
                ("ends_on", models.DateField(blank=True, default=None, null=True)),
                ("from_time", models.TimeField()),
                ("to_time", models.TimeField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="created_by_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="modified_by_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "default_related_name": "related_calendar_activities",
            },
        ),
        migrations.CreateModel(
            name="CalendarActivityTrackingModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ("ss_id", models.IntegerField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "activity",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="event.calendaractivity"),
                ),
            ],
            options={
                "default_related_name": "related_calendar_activity_trackers",
            },
        ),
    ]
