# Generated by Django 4.2.3 on 2023-12-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendaractivity",
            name="event_subtype",
            field=models.CharField(
                choices=[
                    ("session", "Session"),
                    ("course", "Course"),
                    ("learning_path", "Learning Path"),
                    ("advanced_learning_path", "Advanced Learning Path"),
                ],
                default=None,
                max_length=512,
            ),
        ),
        migrations.AddField(
            model_name="calendaractivity",
            name="event_subtype_id",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="calendaractivity",
            name="from_time",
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="calendaractivity",
            name="to_time",
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
