# Generated by Django 4.2.3 on 2024-02-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0004_alter_calendaractivity_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendaractivity",
            name="event_subtype",
            field=models.CharField(
                choices=[
                    ("not_selected", "Not Selected"),
                    ("session", "Session"),
                    ("course", "Course"),
                    ("learning_path", "Learning Path"),
                    ("advanced_learning_path", "Advanced Learning Path"),
                    ("lp_course", "LP Course"),
                    ("alp_learning_path", "ALP Learning Path"),
                ],
                default="not_selected",
                max_length=512,
            ),
        ),
    ]
