# Generated by Django 4.2.3 on 2023-12-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_tenantbanner_tenantconfiguration_footer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantconfiguration',
            name='allowed_user_count',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='tenantconfiguration',
            name='is_chat_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenantconfiguration',
            name='is_forum_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenantconfiguration',
            name='is_mentor_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenantconfiguration',
            name='is_mml_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenantconfiguration',
            name='is_skill_traveller_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenantconfiguration',
            name='is_unlimited_users_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenantconfiguration',
            name='is_yaksha_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
