# Generated by Django 4.2.3 on 2023-12-28 11:29

import apps.common.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("meta", "0009_mmlconfiguration_alp_yakshaconfiguration_alp"),
        ("tenant", "0003_tenantconfiguration_allowed_user_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="data",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="tenant",
            name="is_keycloak",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="TenantAddress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ("ss_id", models.IntegerField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("address_line_one", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("address_line_two", models.CharField(blank=True, default=None, max_length=512, null=True)),
                (
                    "pincode",
                    models.PositiveIntegerField(
                        blank=True, default=None, null=True, validators=[apps.common.validators.validate_pincode]
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="meta.city",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="meta.country",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="created_by_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="modified_by_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="meta.state",
                    ),
                ),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tenant.tenant")),
            ],
            options={
                "abstract": False,
                "default_related_name": "related_tenant_addresses",
            },
        ),
    ]
