# Generated by Django 4.2.3 on 2024-01-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0005_alter_tenant_uuid_alter_tenantaddress_uuid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="issuer_url",
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="tenantaddress",
            name="pincode",
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
    ]
