# Generated by Django 4.2.3 on 2024-01-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0006_tenant_issuer_url_alter_tenantaddress_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantconfiguration',
            name='is_master_calalogue_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
