# Generated by Django 4.2.3 on 2024-01-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0008_alter_tenantbanner_image_alter_tenantlogo_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="client_id",
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="secret_id",
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="secret_value",
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="sso_tenant_id",
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
    ]
