# Generated by Django 4.2.3 on 2024-01-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0009_tenant_client_id_tenant_secret_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantconfiguration",
            name="is_wecp_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tenantconfiguration",
            name="wecp_key",
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
    ]
