# Generated by Django 4.2.3 on 2024-02-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0011_tenantconfiguration_sender_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantconfiguration",
            name="mml_host",
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="tenantconfiguration",
            name="virtutor_host",
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="tenantconfiguration",
            name="yaksha_host",
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
    ]
