# Generated by Django 4.2.3 on 2024-03-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0012_tenantconfiguration_mml_host_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantconfiguration",
            name="is_assignment_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tenantconfiguration",
            name="is_assignment_group_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
