# Generated by Django 4.2.3 on 2024-04-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0014_rename_is_master_calalogue_enabled_tenantconfiguration_is_master_catalogue_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="allowed_login_domain",
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="is_domain_restricted_login",
            field=models.BooleanField(default=False),
        ),
    ]
