# Generated by Django 4.2.3 on 2024-06-10 17:45

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0015_tenant_allowed_login_domain_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantMasterReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True)),
                ("ss_id", models.IntegerField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("user_email", models.CharField()),
                ("user_id", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("user_uuid", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("user_username", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("user_first_name", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("user_last_name", models.CharField(blank=True, default=None, max_length=512, null=True)),
                (
                    "user_group_names",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=512), blank=True, default=None, null=True, size=None
                    ),
                ),
                ("user_employee_id", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("tenant_id", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("tenant_uuid", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("tenant_display_name", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("tenant_tenancy_name", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("learning_type", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("approval_type", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("end_date", models.DateTimeField(blank=True, default=None, null=True)),
                ("is_user_group_enrollment", models.BooleanField(default=False)),
                ("enrolled_user_group_name", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("proficiency", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("learning_points", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("duration", models.CharField(blank=True, default=None, max_length=512, null=True)),
                (
                    "skills",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=512), blank=True, default=None, null=True, size=None
                    ),
                ),
                ("video_progress", models.PositiveIntegerField(blank=True, default=None, null=True)),
                ("start_date", models.DateField(blank=True, default=None, null=True)),
                ("completion_date", models.DateField(blank=True, default=None, null=True)),
                ("learning_status", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("course_id", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("course_uuid", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("course_name", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("course_code", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("lp_id", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("lp_uuid", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("lp_name", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("lp_code", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("alp_id", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("alp_uuid", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("alp_name", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("alp_code", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("st_id", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("st_uuid", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("st_name", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("st_code", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("assignment_id", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("assignment_uuid", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("assignment_name", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("assignment_code", models.CharField(blank=True, default=None, max_length=512, null=True)),
                (
                    "assignment_result",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=512), blank=True, default=None, null=True, size=None
                    ),
                ),
                (
                    "assignment_score",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=512), blank=True, default=None, null=True, size=None
                    ),
                ),
                (
                    "assignment_progress",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=512), blank=True, default=None, null=True, size=None
                    ),
                ),
                ("ag_id", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("ag_uuid", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("ag_name", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("ag_code", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("ag_start_date", models.DateField(blank=True, default=None, null=True)),
                ("ag_completion_date", models.DateField(blank=True, default=None, null=True)),
                ("ag_learning_status", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("assessment_availed_attempts", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("assessment_progress", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("assessment_result", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("assessment_score", models.CharField(blank=True, default=None, max_length=512, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "default_related_name": "related_tenant_master_reports",
            },
        ),
    ]
