# Generated by Django 4.2.3 on 2024-06-11 09:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0016_tenant_api_secret_key"),
        ("tenant", "0016_tenantmasterreport"),
    ]

    operations = []
