# Generated by Django 4.2.3 on 2024-06-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0017_merge_20240611_1446"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantmasterreport",
            name="average_assessment_score",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
