# Generated by Django 4.2.3 on 2023-11-06 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("learning", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFavourite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ("ss_id", models.IntegerField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "favourite_type",
                    models.CharField(
                        choices=[
                            ("category", "Category"),
                            ("skill", "Skill"),
                            ("role", "Role"),
                            ("course", "Course"),
                            ("learning_path", "Learning Path"),
                            ("advanced_learning_path", "Advanced Learning Path"),
                            ("sub_skill", "Sub Skill"),
                            ("sub_role", "Sub Role"),
                            ("skill_traveller", "Skill Traveller"),
                            ("playground", "Playground"),
                            ("playground_group", "Playground Group"),
                        ],
                        max_length=512,
                    ),
                ),
                (
                    "advanced_learning_path",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.advancedlearningpath",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.category",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.course",
                    ),
                ),
                (
                    "learning_path",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.learningpath",
                    ),
                ),
                (
                    "playground",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.playground",
                    ),
                ),
                (
                    "playground_group",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.playgroundgroup",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.categoryrole",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.categoryskill",
                    ),
                ),
                (
                    "skill_traveller",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.skilltraveller",
                    ),
                ),
                (
                    "sub_role",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.subrole",
                    ),
                ),
                (
                    "sub_skill",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.subskill",
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "default_related_name": "related_user_favourites",
            },
        ),
    ]
