# Generated by Django 4.2.3 on 2023-11-07 08:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0002_userfavourite"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserFavourite",
        ),
    ]
