# Generated by Django 4.2.3 on 2023-11-08 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("learning", "0003_delete_userfavourite"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expert",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ("ss_id", models.IntegerField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "learning_type",
                    models.CharField(
                        choices=[
                            ("course", "Course"),
                            ("learning_path", "Learning Path"),
                            ("advanced_learning_path", "Advanced Learning Path"),
                        ],
                        max_length=512,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("approved", "Approved"), ("rejected", "Rejected"), ("pending", "Pending")],
                        default="approved",
                        max_length=512,
                    ),
                ),
                ("is_created_by_admin", models.BooleanField(default=True)),
                (
                    "advanced_learning_path",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.advancedlearningpath",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.course",
                    ),
                ),
                (
                    "learning_path",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.learningpath",
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "default_related_name": "related_experts",
            },
        ),
    ]
