# Generated by Django 4.2.3 on 2023-11-15 06:16

import apps.common.helpers
import apps.common.model_fields
import apps.common.validators
import apps.learning.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("meta", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("learning", "0005_remove_subskill_advanced_learning_path_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignmentDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ("ss_id", models.IntegerField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    apps.common.model_fields.AppFileField(
                        max_size=5,
                        upload_to=apps.common.helpers.file_upload_path,
                        validators=[apps.learning.validators.assignment_file_extension],
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AssignmentImageModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ("ss_id", models.IntegerField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    apps.common.model_fields.AppImageField(max_size=5, upload_to=apps.common.helpers.file_upload_path),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "default_related_name": "related_assignment_images",
            },
        ),
        migrations.CreateModel(
            name="AssignmentTopic",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ("ss_id", models.IntegerField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=512)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "default_related_name": "related_assignment_topics",
            },
        ),
        migrations.CreateModel(
            name="AssignmentSubTopic",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ("ss_id", models.IntegerField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=512)),
                (
                    "topic",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="learning.assignmenttopic"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "default_related_name": "related_assignment_subtopics",
            },
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ("ss_id", models.IntegerField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=512)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("code", models.CharField(blank=True, default=None, max_length=512, null=True, unique=True)),
                ("description", models.TextField(blank=True, default=None, null=True)),
                ("highlight", models.TextField(blank=True, default=None, null=True)),
                ("requirements", models.TextField(blank=True, default=None, null=True)),
                ("prerequisite", models.TextField(blank=True, default=None, null=True)),
                (
                    "proficiency",
                    models.CharField(
                        blank=True,
                        choices=[("basic", "Basic"), ("intermediate", "Intermediate"), ("advance", "Advance")],
                        default=None,
                        max_length=512,
                        null=True,
                    ),
                ),
                (
                    "rating",
                    models.FloatField(
                        blank=True, default=None, null=True, validators=[apps.common.validators.validate_rating]
                    ),
                ),
                ("learning_points", models.PositiveSmallIntegerField(default=0)),
                ("duration", models.PositiveIntegerField(default=0)),
                ("start_date", models.DateField(blank=True, default=None, null=True)),
                ("end_date", models.DateField(blank=True, default=None, null=True)),
                ("is_archive", models.BooleanField(default=False)),
                ("is_draft", models.BooleanField(default=True)),
                ("is_rating_enabled", models.BooleanField(default=False)),
                ("is_feedback_enabled", models.BooleanField(default=False)),
                ("mml_sku_id", models.UUIDField(blank=True, default=None, null=True)),
                ("yaksha_uuid", models.UUIDField(blank=True, default=None, null=True)),
                ("vm_name", models.CharField(blank=True, default=None, max_length=512, null=True)),
                (
                    "type",
                    models.CharField(choices=[("project", "Project"), ("assignment", "Assignment")], max_length=512),
                ),
                (
                    "tool",
                    models.CharField(
                        choices=[("mml", "MML"), ("yaksha", "Yaksha"), ("codelabs", "Codelabs")], max_length=512
                    ),
                ),
                ("reference", models.TextField(blank=True, default=None, null=True)),
                ("version", models.FloatField(blank=True, default=None, null=True)),
                (
                    "assignment_image",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="learning.assignmentimagemodel",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="meta.faculty",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="learning.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="created_by_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="deleted_by_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="learning.assignmentdocument"),
                ),
                ("hashtag", models.ManyToManyField(blank=True, to="meta.hashtag")),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="meta.language",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="modified_by_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("role", models.ManyToManyField(blank=True, to="learning.categoryrole")),
                ("skill", models.ManyToManyField(blank=True, to="learning.categoryskill")),
                (
                    "subtopic",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="learning.assignmentsubtopic",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="learning.assignmenttopic",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_related_name": "related_assignments",
            },
        ),
    ]
