# Generated by Django 4.2.3 on 2023-11-16 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0006_assignmentdocument_assignmentimagemodel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="allowed_attempts",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="assignment",
            name="allowed_submission",
            field=models.CharField(
                blank=True,
                choices=[
                    ("all", "All submissions are allowed"),
                    ("one", "Only one submission allowed"),
                    ("recent", "Only the most recent submission is allowed"),
                ],
                default=None,
                max_length=512,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="extensions_allowed",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="assignment",
            name="files_allowed",
            field=models.CharField(
                blank=True,
                choices=[("single_file", "Single File"), ("multiple_file", "Multiple File")],
                default=None,
                max_length=512,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="reminder_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="assignment",
            name="send_reminder",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assignment",
            name="submission_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("online_file_submission", "Online File Submission"),
                    ("on_paper_submission", "On Paper Submission"),
                    ("observed_in_person", "Observed In Person"),
                ],
                default=None,
                max_length=512,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="file",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="learning.assignmentdocument",
            ),
        ),
    ]
