# Generated by Django 4.2.3 on 2023-11-21 05:56

import apps.common.helpers
import apps.common.model_fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0008_assignment_evaluation_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningUpdateImageModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ("ss_id", models.IntegerField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    apps.common.model_fields.AppImageField(max_size=5, upload_to=apps.common.helpers.file_upload_path),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LearningUpdate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ("ss_id", models.IntegerField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=512)),
                ("description", models.TextField(blank=True, default=None, null=True)),
                (
                    "learning_type",
                    models.CharField(
                        choices=[
                            ("course", "Course"),
                            ("learning_path", "Learning Path"),
                            ("advanced_learning_path", "Advanced Learning Path"),
                            ("skill_traveller", "Skill Traveller"),
                        ],
                        max_length=512,
                    ),
                ),
                (
                    "update_type",
                    models.CharField(
                        choices=[
                            ("announcement", "Announcement"),
                            ("broadcast", "Broadcast"),
                            ("notification", "Notification"),
                            ("alert", "Alert"),
                        ],
                        max_length=512,
                    ),
                ),
                (
                    "advanced_learning_path",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.advancedlearningpath",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.course",
                    ),
                ),
                (
                    "learning_path",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.learningpath",
                    ),
                ),
                (
                    "learning_update_image",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="learning.learningupdateimagemodel",
                    ),
                ),
                (
                    "skill_traveller",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.skilltraveller",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "default_related_name": "related_learning_updates",
            },
        ),
    ]
