# Generated by Django 4.2.3 on 2023-11-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0011_assignment_max_allowed_moduleassignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogue",
            name="assignment",
            field=models.ManyToManyField(blank=True, to="learning.assignment"),
        ),
        migrations.AddField(
            model_name="catalogue",
            name="category",
            field=models.ManyToManyField(blank=True, to="learning.category"),
        ),
        migrations.AddField(
            model_name="catalogue",
            name="role",
            field=models.ManyToManyField(blank=True, to="learning.categoryrole"),
        ),
        migrations.AddField(
            model_name="catalogue",
            name="skill",
            field=models.ManyToManyField(blank=True, to="learning.categoryskill"),
        ),
    ]
