# Generated by Django 4.2.3 on 2023-11-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0014_remove_advancedlearningpath_credit_score_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="advancedlearningpathresource",
            name="is_upload_success",
        ),
        migrations.RemoveField(
            model_name="advancedlearningpathresource",
            name="is_uploaded",
        ),
        migrations.RemoveField(
            model_name="assignmentresource",
            name="is_upload_success",
        ),
        migrations.RemoveField(
            model_name="assignmentresource",
            name="is_uploaded",
        ),
        migrations.RemoveField(
            model_name="courseresource",
            name="is_upload_success",
        ),
        migrations.RemoveField(
            model_name="courseresource",
            name="is_uploaded",
        ),
        migrations.RemoveField(
            model_name="coursesubmodule",
            name="url",
        ),
        migrations.RemoveField(
            model_name="learningpathresource",
            name="is_upload_success",
        ),
        migrations.RemoveField(
            model_name="learningpathresource",
            name="is_uploaded",
        ),
        migrations.RemoveField(
            model_name="skilltravellerresource",
            name="is_upload_success",
        ),
        migrations.RemoveField(
            model_name="skilltravellerresource",
            name="is_uploaded",
        ),
        migrations.AddField(
            model_name="advancedlearningpathresource",
            name="upload_status",
            field=models.CharField(
                choices=[
                    ("initiated", "Initiated"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="completed",
                max_length=512,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assignmentresource",
            name="upload_status",
            field=models.CharField(
                choices=[
                    ("initiated", "Initiated"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="completed",
                max_length=512,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="courseresource",
            name="upload_status",
            field=models.CharField(
                choices=[
                    ("initiated", "Initiated"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="completed",
                max_length=512,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="coursesubmodule",
            name="custom_url",
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="coursesubmodule",
            name="file_url",
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="coursesubmodule",
            name="type",
            field=models.CharField(
                choices=[("video", "Video"), ("file", "File"), ("custom_url", "Custom URL")],
                default="custom_url",
                max_length=512,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="coursesubmodule",
            name="upload_status",
            field=models.CharField(
                choices=[
                    ("initiated", "Initiated"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="completed",
                max_length=512,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="learningpathresource",
            name="upload_status",
            field=models.CharField(
                choices=[
                    ("initiated", "Initiated"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="completed",
                max_length=512,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="skilltravellerresource",
            name="upload_status",
            field=models.CharField(
                choices=[
                    ("initiated", "Initiated"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="completed",
                max_length=512,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="advancedlearningpathresource",
            name="type",
            field=models.CharField(
                choices=[
                    ("video", "Video"),
                    ("file", "File"),
                    ("custom_url", "Custom URL"),
                    ("course_within_catalogue", "Course within catalogue"),
                ],
                max_length=512,
            ),
        ),
        migrations.AlterField(
            model_name="assignmentresource",
            name="type",
            field=models.CharField(
                choices=[
                    ("video", "Video"),
                    ("file", "File"),
                    ("custom_url", "Custom URL"),
                    ("course_within_catalogue", "Course within catalogue"),
                ],
                max_length=512,
            ),
        ),
        migrations.AlterField(
            model_name="coursemodule",
            name="position",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="courseresource",
            name="type",
            field=models.CharField(
                choices=[
                    ("video", "Video"),
                    ("file", "File"),
                    ("custom_url", "Custom URL"),
                    ("course_within_catalogue", "Course within catalogue"),
                ],
                max_length=512,
            ),
        ),
        migrations.AlterField(
            model_name="coursesubmodule",
            name="duration",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="coursesubmodule",
            name="position",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="learningpathresource",
            name="type",
            field=models.CharField(
                choices=[
                    ("video", "Video"),
                    ("file", "File"),
                    ("custom_url", "Custom URL"),
                    ("course_within_catalogue", "Course within catalogue"),
                ],
                max_length=512,
            ),
        ),
        migrations.AlterField(
            model_name="skilltravellerresource",
            name="type",
            field=models.CharField(
                choices=[
                    ("video", "Video"),
                    ("file", "File"),
                    ("custom_url", "Custom URL"),
                    ("course_within_catalogue", "Course within catalogue"),
                ],
                max_length=512,
            ),
        ),
    ]
