# Generated by Django 4.2.3 on 2023-12-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0014_remove_advancedlearningpath_credit_score_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="allowed_submission",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="extensions_allowed",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="files_allowed",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="max_allowed",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="submission_type",
        ),
        migrations.AddField(
            model_name="assignment",
            name="enable_submission",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="catalogue",
            name="is_assessment_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="catalogue",
            name="is_labs_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="catalogue",
            name="is_locked",
            field=models.BooleanField(default=False),
        ),
    ]
