# Generated by Django 4.2.3 on 2023-12-05 10:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0015_remove_advancedlearningpathresource_is_upload_success_and_more"),
        ("learning", "0015_remove_assignment_allowed_submission_and_more"),
    ]

    operations = []
