# Generated by Django 4.2.3 on 2023-12-05 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0016_merge_20231205_1600"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogue",
            name="no_of_assignment",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="category",
            name="no_of_assignment",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="categoryrole",
            name="no_of_assignment",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="categoryskill",
            name="no_of_assignment",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="advancedlearningpath",
            name="rating",
            field=models.FloatField(
                blank=True,
                default=None,
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)],
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="rating",
            field=models.FloatField(
                blank=True,
                default=None,
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)],
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="rating",
            field=models.FloatField(
                blank=True,
                default=None,
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)],
            ),
        ),
        migrations.AlterField(
            model_name="learningpath",
            name="rating",
            field=models.FloatField(
                blank=True,
                default=None,
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)],
            ),
        ),
        migrations.AlterField(
            model_name="playground",
            name="rating",
            field=models.FloatField(
                blank=True,
                default=None,
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)],
            ),
        ),
        migrations.AlterField(
            model_name="playgroundgroup",
            name="rating",
            field=models.FloatField(
                blank=True,
                default=None,
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)],
            ),
        ),
        migrations.AlterField(
            model_name="skilltraveller",
            name="rating",
            field=models.FloatField(
                blank=True,
                default=None,
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)],
            ),
        ),
    ]
