# Generated by Django 4.2.3 on 2023-12-07 09:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0017_catalogue_no_of_assignment_category_no_of_assignment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ("ss_id", models.IntegerField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("module_assignment", "Module Assignment"), ("final_assignment", "Final Assignment")],
                        max_length=512,
                    ),
                ),
                ("sequence", models.PositiveIntegerField(default=0)),
                (
                    "assignment",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="learning.assignment"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="learning.course",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "default_related_name": "related_course_assignments",
            },
        ),
        migrations.RenameField(
            model_name="coursemodule",
            old_name="position",
            new_name="sequence",
        ),
        migrations.RenameField(
            model_name="coursesubmodule",
            old_name="position",
            new_name="sequence",
        ),
        migrations.DeleteModel(
            name="ModuleAssignment",
        ),
        migrations.AddField(
            model_name="courseassignment",
            name="module",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="learning.coursemodule",
            ),
        ),
    ]
