# Generated by Django 4.2.3 on 2023-12-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0018_courseassignment_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="courseassessment",
            options={"default_related_name": "related_course_assessments", "ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="courseassessment",
            name="allowed_attempts",
        ),
        migrations.RemoveField(
            model_name="courseassessment",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="courseassessment",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="courseassessment",
            name="is_shuffling_enabled",
        ),
        migrations.RemoveField(
            model_name="courseassessment",
            name="modified_by",
        ),
        migrations.RemoveField(
            model_name="courseassessment",
            name="name",
        ),
        migrations.RemoveField(
            model_name="courseassessment",
            name="pass_percentage",
        ),
        migrations.RemoveField(
            model_name="courseassessment",
            name="result_type",
        ),
        migrations.RemoveField(
            model_name="courseassessment",
            name="yaksha_id",
        ),
        migrations.AddField(
            model_name="courseassessment",
            name="sequence",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
