# Generated by Django 4.2.3 on 2023-12-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0019_alter_courseassessment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseassessment",
            name="name",
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
    ]
