# Generated by Django 4.2.3 on 2023-12-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0020_courseassessment_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseassessment",
            name="is_practice",
            field=models.BooleanField(default=False),
        ),
    ]
