# Generated by Django 4.2.3 on 2023-12-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0023_scorm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursesubmodule",
            name="type",
            field=models.CharField(
                choices=[("video", "Video"), ("file", "File"), ("custom_url", "Custom URL"), ("scorm", "Scorm")],
                max_length=512,
            ),
        ),
    ]
