# Generated by Django 4.2.3 on 2023-12-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0008_feedbacktemplate_feedbacktemplatequestion_and_more'),
        ('learning', '0024_alter_coursesubmodule_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedlearningpath',
            name='feedback_template',
            field=models.ManyToManyField(blank=True, to='meta.feedbacktemplate'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='feedback_template',
            field=models.ManyToManyField(blank=True, to='meta.feedbacktemplate'),
        ),
        migrations.AddField(
            model_name='course',
            name='feedback_template',
            field=models.ManyToManyField(blank=True, to='meta.feedbacktemplate'),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='feedback_template',
            field=models.ManyToManyField(blank=True, to='meta.feedbacktemplate'),
        ),
        migrations.AddField(
            model_name='playground',
            name='feedback_template',
            field=models.ManyToManyField(blank=True, to='meta.feedbacktemplate'),
        ),
        migrations.AddField(
            model_name='playgroundgroup',
            name='feedback_template',
            field=models.ManyToManyField(blank=True, to='meta.feedbacktemplate'),
        ),
        migrations.AddField(
            model_name='skilltraveller',
            name='feedback_template',
            field=models.ManyToManyField(blank=True, to='meta.feedbacktemplate'),
        ),
    ]
