# Generated by Django 4.2.3 on 2023-12-20 15:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0026_alter_advancedlearningpathresource_custom_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ALPAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ("ss_id", models.IntegerField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveIntegerField(default=0)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("dependent_assignment", "Dependent Assignment"),
                            ("final_assignment", "Final Assignment"),
                        ],
                        max_length=512,
                    ),
                ),
                (
                    "alp",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="learning.advancedlearningpath",
                    ),
                ),
                (
                    "alp_lp",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="learning.alplearningpath",
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="learning.assignment"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "default_related_name": "related_alp_assignments",
            },
        ),
        migrations.CreateModel(
            name="ALPAssessment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ("ss_id", models.IntegerField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(blank=True, default=None, max_length=512, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("dependent_assessment", "Dependent Assessment"),
                            ("final_assessment", "Final Assessment"),
                        ],
                        max_length=512,
                    ),
                ),
                ("yaksha_uuid", models.UUIDField()),
                ("is_practice", models.BooleanField(default=False)),
                (
                    "alp",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="learning.advancedlearningpath",
                    ),
                ),
                (
                    "alp_lp",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="learning.alplearningpath",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "default_related_name": "related_alp_assessments",
            },
        ),
    ]
