# Generated by Django 4.2.3 on 2023-12-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0027_alpassignment_alpassessment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advancedlearningpathresource",
            name="custom_url",
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="assignmentresource",
            name="custom_url",
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="courseresource",
            name="custom_url",
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="coursesubmodule",
            name="custom_url",
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="learningpathresource",
            name="custom_url",
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="skilltravellerresource",
            name="custom_url",
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
    ]
