# Generated by Django 4.2.3 on 2023-12-29 13:21

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("access_control", "0004_alter_policy_uuid_alter_policycategory_uuid_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("learning", "0029_alter_advancedlearningpath_uuid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="catalogue",
            name="user_group",
        ),
        migrations.AddField(
            model_name="catalogue",
            name="ccms_alp",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.UUIDField(), blank=True, default=None, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="catalogue",
            name="ccms_assignment",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.UUIDField(), blank=True, default=None, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="catalogue",
            name="ccms_course",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.UUIDField(), blank=True, default=None, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="catalogue",
            name="ccms_lp",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.UUIDField(), blank=True, default=None, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="catalogue",
            name="ccms_st",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.UUIDField(), blank=True, default=None, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="catalogue",
            name="ccms_tp",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.UUIDField(), blank=True, default=None, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="catalogue",
            name="ccms_tpg",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.UUIDField(), blank=True, default=None, null=True, size=None
            ),
        ),
        migrations.CreateModel(
            name="CatalogueRelation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True)),
                ("ss_id", models.IntegerField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("ccms_id", models.UUIDField(blank=True, default=None, null=True, unique=True)),
                ("is_ccms_obj", models.BooleanField(default=False)),
                (
                    "catalogue",
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="learning.catalogue",
                    ),
                ),
                ("user", models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ("user_group", models.ManyToManyField(blank=True, to="access_control.usergroup")),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "default_related_name": "related_catalogue_relations",
            },
        ),
    ]
