# Generated by Django 4.2.3 on 2024-01-06 11:37

import apps.common.helpers
import apps.common.model_fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0031_alter_catalogue_name_alter_category_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advancedlearningpathimagemodel",
            name="image",
            field=apps.common.model_fields.AppImageField(
                max_length=512, max_size=5, upload_to=apps.common.helpers.file_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="assignmentimagemodel",
            name="image",
            field=apps.common.model_fields.AppImageField(
                max_length=512, max_size=5, upload_to=apps.common.helpers.file_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="categoryimagemodel",
            name="image",
            field=apps.common.model_fields.AppImageField(
                max_length=512, max_size=5, upload_to=apps.common.helpers.file_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="categoryroleimagemodel",
            name="image",
            field=apps.common.model_fields.AppImageField(
                max_length=512, max_size=5, upload_to=apps.common.helpers.file_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="categoryskillimagemodel",
            name="image",
            field=apps.common.model_fields.AppImageField(
                max_length=512, max_size=5, upload_to=apps.common.helpers.file_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="courseimagemodel",
            name="image",
            field=apps.common.model_fields.AppImageField(
                max_length=512, max_size=5, upload_to=apps.common.helpers.file_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="learningpathimagemodel",
            name="image",
            field=apps.common.model_fields.AppImageField(
                max_length=512, max_size=5, upload_to=apps.common.helpers.file_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="learningupdateimagemodel",
            name="image",
            field=apps.common.model_fields.AppImageField(
                max_length=512, max_size=5, upload_to=apps.common.helpers.file_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="playgroundgroupimage",
            name="image",
            field=apps.common.model_fields.AppImageField(
                max_length=512, max_size=5, upload_to=apps.common.helpers.file_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="playgroundimage",
            name="image",
            field=apps.common.model_fields.AppImageField(
                max_length=512, max_size=5, upload_to=apps.common.helpers.file_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="skilltravellerimagemodel",
            name="image",
            field=apps.common.model_fields.AppImageField(
                max_length=512, max_size=5, upload_to=apps.common.helpers.file_upload_path
            ),
        ),
    ]
