# Generated by Django 4.2.3 on 2024-01-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0033_alter_advancedlearningpath_proficiency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advancedlearningpathresource",
            name="file_url",
            field=models.URLField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="assignmentresource",
            name="file_url",
            field=models.URLField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="courseresource",
            name="file_url",
            field=models.URLField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="coursesubmodule",
            name="file_url",
            field=models.URLField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="learningpathresource",
            name="file_url",
            field=models.URLField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="skilltravellerresource",
            name="file_url",
            field=models.URLField(blank=True, default=None, max_length=512, null=True),
        ),
    ]
