# Generated by Django 4.2.3 on 2024-01-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0034_alter_advancedlearningpathresource_file_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advancedlearningpathresource",
            name="custom_url",
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="advancedlearningpathresource",
            name="file_url",
            field=models.URLField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="assignmentresource",
            name="custom_url",
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="assignmentresource",
            name="file_url",
            field=models.URLField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="courseresource",
            name="custom_url",
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="courseresource",
            name="file_url",
            field=models.URLField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="coursesubmodule",
            name="custom_url",
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="coursesubmodule",
            name="file_url",
            field=models.URLField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="learningpathresource",
            name="custom_url",
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="learningpathresource",
            name="file_url",
            field=models.URLField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="skilltravellerresource",
            name="custom_url",
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="skilltravellerresource",
            name="file_url",
            field=models.URLField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
