# Generated by Django 4.2.3 on 2024-01-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0036_coursesubmodule_evaluation_type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="alpassessment",
            old_name="yaksha_uuid",
            new_name="assessment_uuid",
        ),
        migrations.RenameField(
            model_name="assignment",
            old_name="yaksha_uuid",
            new_name="assessment_uuid",
        ),
        migrations.RenameField(
            model_name="courseassessment",
            old_name="yaksha_uuid",
            new_name="assessment_uuid",
        ),
        migrations.RenameField(
            model_name="lpassessment",
            old_name="yaksha_uuid",
            new_name="assessment_uuid",
        ),
        migrations.AddField(
            model_name="alpassessment",
            name="provider_type",
            field=models.CharField(
                blank=True, choices=[("yaksha", "Yaksha"), ("wecp", "Wecp")], default=None, max_length=512, null=True
            ),
        ),
        migrations.AddField(
            model_name="courseassessment",
            name="provider_type",
            field=models.CharField(
                blank=True, choices=[("yaksha", "Yaksha"), ("wecp", "Wecp")], default=None, max_length=512, null=True
            ),
        ),
        migrations.AddField(
            model_name="lpassessment",
            name="provider_type",
            field=models.CharField(
                blank=True, choices=[("yaksha", "Yaksha"), ("wecp", "Wecp")], default=None, max_length=512, null=True
            ),
        ),
    ]
