# Generated by Django 4.2.3 on 2024-01-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0037_rename_yaksha_uuid_alpassessment_assessment_uuid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogue",
            name="is_self_enroll_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
