# Generated by Django 4.2.3 on 2024-02-01 11:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0038_catalogue_is_self_enroll_enabled"),
    ]

    operations = [
        migrations.RenameField(
            model_name="advancedlearningpath",
            old_name="advanced_learning_path_image",
            new_name="image",
        ),
        migrations.RenameField(
            model_name="assignment",
            old_name="assignment_image",
            new_name="image",
        ),
        migrations.RenameField(
            model_name="category",
            old_name="category_image",
            new_name="image",
        ),
        migrations.RenameField(
            model_name="categoryrole",
            old_name="role_image",
            new_name="image",
        ),
        migrations.RenameField(
            model_name="categoryskill",
            old_name="skill_image",
            new_name="image",
        ),
        migrations.RenameField(
            model_name="course",
            old_name="course_image",
            new_name="image",
        ),
        migrations.RenameField(
            model_name="learningpath",
            old_name="learning_path_image",
            new_name="image",
        ),
        migrations.RenameField(
            model_name="playground",
            old_name="playground_image",
            new_name="image",
        ),
        migrations.RenameField(
            model_name="playgroundgroup",
            old_name="playground_group_image",
            new_name="image",
        ),
        migrations.RenameField(
            model_name="skilltraveller",
            old_name="skill_traveller_image",
            new_name="image",
        ),
    ]
