# Generated by Django 4.2.3 on 2024-03-06 09:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0040_alter_skilltraveller_journey_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="STAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True)),
                ("ss_id", models.IntegerField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveIntegerField(default=0)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("dependent_assignment", "Dependent Assignment"),
                            ("final_assignment", "Final Assignment"),
                        ],
                        max_length=512,
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="learning.assignment"),
                ),
                (
                    "skill_traveller",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.skilltraveller",
                    ),
                ),
                (
                    "st_course",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.skilltravellercourse",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "default_related_name": "related_st_assignments",
            },
        ),
        migrations.CreateModel(
            name="STAssessment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True)),
                ("ss_id", models.IntegerField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, default=None, max_length=512, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("dependent_assessment", "Dependent Assessment"),
                            ("final_assessment", "Final Assessment"),
                        ],
                        max_length=512,
                    ),
                ),
                (
                    "provider_type",
                    models.CharField(
                        blank=True,
                        choices=[("yaksha", "Yaksha"), ("wecp", "Wecp")],
                        default=None,
                        max_length=512,
                        null=True,
                    ),
                ),
                ("assessment_uuid", models.UUIDField()),
                ("is_practice", models.BooleanField(default=False)),
                ("sequence", models.PositiveIntegerField(default=0)),
                (
                    "skill_traveller",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.skilltraveller",
                    ),
                ),
                (
                    "st_course",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.skilltravellercourse",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "default_related_name": "related_st_assessments",
            },
        ),
    ]
