# Generated by Django 4.2.3 on 2024-03-13 09:50

import apps.common.helpers
import apps.common.model_fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("meta", "0012_alter_facultyimagemodel_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("learning", "0041_stassignment_stassessment"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignmentGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True)),
                ("ss_id", models.IntegerField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=512)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("code", models.CharField(blank=True, default=None, max_length=512, null=True, unique=True)),
                ("description", models.TextField(blank=True, default=None, null=True)),
                ("highlight", models.TextField(blank=True, default=None, null=True)),
                ("prerequisite", models.TextField(blank=True, default=None, null=True)),
                (
                    "proficiency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("basic", "Basic"),
                            ("intermediate", "Intermediate"),
                            ("advance", "Advance"),
                            ("comprehensive", "Comprehensive"),
                            ("certification", "Certification"),
                            ("conversant", "Conversant"),
                            ("general", "General"),
                        ],
                        default=None,
                        max_length=512,
                        null=True,
                    ),
                ),
                (
                    "rating",
                    models.FloatField(
                        blank=True,
                        default=None,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("learning_points", models.PositiveSmallIntegerField(default=0)),
                ("duration", models.PositiveIntegerField(default=0)),
                ("start_date", models.DateField(blank=True, default=None, null=True)),
                ("end_date", models.DateField(blank=True, default=None, null=True)),
                ("is_archive", models.BooleanField(default=False)),
                ("is_draft", models.BooleanField(default=True)),
                ("is_rating_enabled", models.BooleanField(default=False)),
                ("is_feedback_enabled", models.BooleanField(default=False)),
                ("no_of_assignments", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="learning.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="created_by_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="deleted_by_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("feedback_template", models.ManyToManyField(blank=True, to="meta.feedbacktemplate")),
                ("hashtag", models.ManyToManyField(blank=True, to="meta.hashtag")),
            ],
            options={
                "abstract": False,
                "default_related_name": "related_assignment_groups",
            },
        ),
        migrations.CreateModel(
            name="AssignmentGroupImageModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True)),
                ("ss_id", models.IntegerField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    apps.common.model_fields.AppImageField(
                        max_length=512, max_size=5, upload_to=apps.common.helpers.file_upload_path
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "default_related_name": "related_assignment_group_images",
            },
        ),
        migrations.AddField(
            model_name="assignment",
            name="guidance_text",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="assignment",
            name="guidance_type",
            field=models.CharField(
                choices=[("guided", "Guided"), ("unguided", "Unguided")], default="guided", max_length=512
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="type",
            field=models.CharField(
                choices=[("project", "Project"), ("assignment", "Assignment"), ("challenges", "Challenges")],
                max_length=512,
            ),
        ),
        migrations.CreateModel(
            name="AssignmentRelation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True)),
                ("ss_id", models.IntegerField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveIntegerField()),
                ("is_mandatory", models.BooleanField(default=False)),
                (
                    "assignment",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="learning.assignment"),
                ),
                (
                    "assignment_group",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="learning.assignmentgroup"),
                ),
            ],
            options={
                "default_related_name": "related_assignment_relations",
            },
        ),
        migrations.AddField(
            model_name="assignmentgroup",
            name="image",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="learning.assignmentgroupimagemodel",
            ),
        ),
        migrations.AddField(
            model_name="assignmentgroup",
            name="language",
            field=models.ForeignKey(
                blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to="meta.language"
            ),
        ),
        migrations.AddField(
            model_name="assignmentgroup",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="modified_by_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assignmentgroup",
            name="role",
            field=models.ManyToManyField(blank=True, to="learning.categoryrole"),
        ),
        migrations.AddField(
            model_name="assignmentgroup",
            name="skill",
            field=models.ManyToManyField(blank=True, to="learning.categoryskill"),
        ),
        migrations.AddField(
            model_name="catalogue",
            name="assignment_group",
            field=models.ManyToManyField(blank=True, to="learning.assignmentgroup"),
        ),
    ]
