# Generated by Django 4.2.3 on 2024-03-18 07:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("learning", "0043_catalogue_ccms_assignment_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursesubmodule",
            name="author",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
