# Generated by Django 4.2.3 on 2024-03-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0044_coursesubmodule_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="advancedlearningpath",
            name="is_notify_users",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="advancedlearningpath",
            name="is_retired",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="advancedlearningpath",
            name="notify_days",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="advancedlearningpath",
            name="retirement_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="assignment",
            name="is_notify_users",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assignment",
            name="is_retired",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assignment",
            name="notify_days",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="assignment",
            name="retirement_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="assignmentgroup",
            name="is_notify_users",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assignmentgroup",
            name="is_retired",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assignmentgroup",
            name="notify_days",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="assignmentgroup",
            name="retirement_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="is_notify_users",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="course",
            name="is_retired",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="course",
            name="notify_days",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="retirement_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="learningpath",
            name="is_notify_users",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="learningpath",
            name="is_retired",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="learningpath",
            name="notify_days",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="learningpath",
            name="retirement_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="playground",
            name="is_notify_users",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="playground",
            name="is_retired",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="playground",
            name="notify_days",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="playground",
            name="retirement_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="playgroundgroup",
            name="is_notify_users",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="playgroundgroup",
            name="is_retired",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="playgroundgroup",
            name="notify_days",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="playgroundgroup",
            name="retirement_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="skilltraveller",
            name="is_notify_users",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="skilltraveller",
            name="is_retired",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="skilltraveller",
            name="notify_days",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="skilltraveller",
            name="retirement_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
