# Generated by Django 4.2.3 on 2024-04-03 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("access", "0008_alter_userskilldetail_proficiency"),
        ("learning", "0045_advancedlearningpath_is_notify_users_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="skillontology",
            options={"default_related_name": "related_skill_ontologies", "ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="skillontology",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="skillontology",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="skillontology",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="skillontology",
            name="description",
        ),
        migrations.RemoveField(
            model_name="skillontology",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="skillontology",
            name="is_archive",
        ),
        migrations.RemoveField(
            model_name="skillontology",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="skillontology",
            name="is_draft",
        ),
        migrations.RemoveField(
            model_name="skillontology",
            name="is_popular",
        ),
        migrations.RemoveField(
            model_name="skillontology",
            name="is_recommended",
        ),
        migrations.RemoveField(
            model_name="skillontology",
            name="modified_by",
        ),
        migrations.RemoveField(
            model_name="skillontology",
            name="skill",
        ),
        migrations.AddField(
            model_name="assignment",
            name="is_feedback_mandatory",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assignmentgroup",
            name="is_feedback_mandatory",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="skillontology",
            name="advanced_learning_path",
            field=models.ManyToManyField(blank=True, to="learning.advancedlearningpath"),
        ),
        migrations.AddField(
            model_name="skillontology",
            name="assignment",
            field=models.ManyToManyField(blank=True, to="learning.assignment"),
        ),
        migrations.AddField(
            model_name="skillontology",
            name="assignment_group",
            field=models.ManyToManyField(blank=True, to="learning.assignmentgroup"),
        ),
        migrations.AddField(
            model_name="skillontology",
            name="course",
            field=models.ManyToManyField(blank=True, to="learning.course"),
        ),
        migrations.AddField(
            model_name="skillontology",
            name="current_skill_detail",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_current_skill_detail",
                to="access.userskilldetail",
            ),
        ),
        migrations.AddField(
            model_name="skillontology",
            name="desired_skill_detail",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_desired_skill_detail",
                to="access.userskilldetail",
            ),
        ),
        migrations.AddField(
            model_name="skillontology",
            name="learning_path",
            field=models.ManyToManyField(blank=True, to="learning.learningpath"),
        ),
        migrations.AddField(
            model_name="skillontology",
            name="skill_traveller",
            field=models.ManyToManyField(blank=True, to="learning.skilltraveller"),
        ),
        migrations.AddField(
            model_name="skillontology",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="RoleOntology",
        ),
    ]
