# Generated by Django 4.2.3 on 2024-04-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0046_alter_skillontology_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skilltraveller",
            name="journey_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("hiking", "Hiking"),
                    ("trekking", "Trekking"),
                    ("weekend_gateway", "Weekend Gateway"),
                    ("business_travel", "Business Travel"),
                    ("event_trip", "Event Trip"),
                    ("long_term_slow_travel", "Long Term Slow Travel"),
                ],
                default=None,
                max_length=512,
                null=True,
            ),
        ),
    ]
