# Generated by Django 4.2.3 on 2023-11-06 06:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("learning", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCourseModuleTrackingModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ("ss_id", models.IntegerField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "progress",
                    models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
                ),
                ("is_started", models.BooleanField(default=False)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="created_by_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enrolled_to",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("module", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="learning.coursemodule")),
            ],
            options={
                "abstract": False,
                "default_related_name": "related_course_module_trackers",
            },
        ),
        migrations.CreateModel(
            name="UserCourseTrackingModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ("ss_id", models.IntegerField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("actionee_id", models.PositiveIntegerField(blank=True, default=None, null=True)),
                ("actionee_name", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("reason", models.TextField(blank=True, default=None, null=True)),
                ("action_date", models.DateField(blank=True, default=None, null=True)),
                (
                    "action",
                    models.CharField(
                        choices=[("approved", "Approved"), ("rejected", "Rejected"), ("pending", "Pending")],
                        default="pending",
                        max_length=512,
                    ),
                ),
                ("is_super_admin_approval", models.BooleanField(default=False)),
                ("is_tenant_admin_approval", models.BooleanField(default=False)),
                ("is_self_enrolled", models.BooleanField(default=False)),
                (
                    "progress",
                    models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
                ),
                ("is_started", models.BooleanField(default=False)),
                ("is_completed", models.BooleanField(default=False)),
                ("valid_till", models.DateField()),
                ("last_accessed_on", models.DateTimeField(blank=True, default=None, null=True)),
                ("course", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="learning.course")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="created_by_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enrolled_to",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_related_name": "related_user_course_trackers",
            },
        ),
        migrations.CreateModel(
            name="UserCourseSubModuleTrackingModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ("ss_id", models.IntegerField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "progress",
                    models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
                ),
                ("is_started", models.BooleanField(default=False)),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_duration", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="created_by_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enrolled_to",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_tracker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="my_learning.usercoursemoduletrackingmodel"
                    ),
                ),
                (
                    "sub_module",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="learning.coursesubmodule"),
                ),
            ],
            options={
                "abstract": False,
                "default_related_name": "related_course_sub_module_trackers",
            },
        ),
        migrations.CreateModel(
            name="UserCourseNotes",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ("ss_id", models.IntegerField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("notes", models.TextField()),
                ("time_stamp", models.FloatField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="created_by_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="deleted_by_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="modified_by_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sub_module",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="learning.coursesubmodule"),
                ),
            ],
            options={
                "default_related_name": "related_user_course_notes",
            },
        ),
        migrations.AddField(
            model_name="usercoursemoduletrackingmodel",
            name="parent_tracker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="my_learning.usercoursetrackingmodel"
            ),
        ),
        migrations.CreateModel(
            name="UserCourseBookMark",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ("ss_id", models.IntegerField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="created_by_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sub_module",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="learning.coursesubmodule"),
                ),
            ],
            options={
                "default_related_name": "related_user_course_bookmarks",
            },
        ),
        migrations.CreateModel(
            name="SubSkillTrackingModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ("ss_id", models.IntegerField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("actionee_id", models.PositiveIntegerField(blank=True, default=None, null=True)),
                ("actionee_name", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("reason", models.TextField(blank=True, default=None, null=True)),
                ("action_date", models.DateField(blank=True, default=None, null=True)),
                (
                    "action",
                    models.CharField(
                        choices=[("approved", "Approved"), ("rejected", "Rejected"), ("pending", "Pending")],
                        default="pending",
                        max_length=512,
                    ),
                ),
                ("is_super_admin_approval", models.BooleanField(default=False)),
                ("is_tenant_admin_approval", models.BooleanField(default=False)),
                ("is_self_enrolled", models.BooleanField(default=False)),
                (
                    "progress",
                    models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
                ),
                ("is_started", models.BooleanField(default=False)),
                ("is_completed", models.BooleanField(default=False)),
                ("last_accessed_on", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="created_by_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enrolled_to",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("sub_skill", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="learning.subskill")),
            ],
            options={
                "abstract": False,
                "default_related_name": "related_user_sub_skill_trackers",
            },
        ),
        migrations.CreateModel(
            name="SubRoleTrackingModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ("ss_id", models.IntegerField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("actionee_id", models.PositiveIntegerField(blank=True, default=None, null=True)),
                ("actionee_name", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("reason", models.TextField(blank=True, default=None, null=True)),
                ("action_date", models.DateField(blank=True, default=None, null=True)),
                (
                    "action",
                    models.CharField(
                        choices=[("approved", "Approved"), ("rejected", "Rejected"), ("pending", "Pending")],
                        default="pending",
                        max_length=512,
                    ),
                ),
                ("is_super_admin_approval", models.BooleanField(default=False)),
                ("is_tenant_admin_approval", models.BooleanField(default=False)),
                ("is_self_enrolled", models.BooleanField(default=False)),
                (
                    "progress",
                    models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
                ),
                ("is_started", models.BooleanField(default=False)),
                ("is_completed", models.BooleanField(default=False)),
                ("last_accessed_on", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="created_by_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enrolled_to",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("sub_role", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="learning.subrole")),
            ],
            options={
                "abstract": False,
                "default_related_name": "related_user_sub_role_trackers",
            },
        ),
        migrations.CreateModel(
            name="SkillTravellerTrackingModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ("ss_id", models.IntegerField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("actionee_id", models.PositiveIntegerField(blank=True, default=None, null=True)),
                ("actionee_name", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("reason", models.TextField(blank=True, default=None, null=True)),
                ("action_date", models.DateField(blank=True, default=None, null=True)),
                (
                    "action",
                    models.CharField(
                        choices=[("approved", "Approved"), ("rejected", "Rejected"), ("pending", "Pending")],
                        default="pending",
                        max_length=512,
                    ),
                ),
                ("is_super_admin_approval", models.BooleanField(default=False)),
                ("is_tenant_admin_approval", models.BooleanField(default=False)),
                ("is_self_enrolled", models.BooleanField(default=False)),
                (
                    "progress",
                    models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
                ),
                ("is_started", models.BooleanField(default=False)),
                ("is_completed", models.BooleanField(default=False)),
                ("valid_till", models.DateField()),
                ("last_accessed_on", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="created_by_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enrolled_to",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "skill_traveller",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="learning.skilltraveller"),
                ),
            ],
            options={
                "abstract": False,
                "default_related_name": "related_user_skill_traveller_trackers",
            },
        ),
        migrations.CreateModel(
            name="PlaygroundTrackingModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ("ss_id", models.IntegerField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("actionee_id", models.PositiveIntegerField(blank=True, default=None, null=True)),
                ("actionee_name", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("reason", models.TextField(blank=True, default=None, null=True)),
                ("action_date", models.DateField(blank=True, default=None, null=True)),
                (
                    "action",
                    models.CharField(
                        choices=[("approved", "Approved"), ("rejected", "Rejected"), ("pending", "Pending")],
                        default="pending",
                        max_length=512,
                    ),
                ),
                ("is_super_admin_approval", models.BooleanField(default=False)),
                ("is_tenant_admin_approval", models.BooleanField(default=False)),
                ("is_self_enrolled", models.BooleanField(default=False)),
                (
                    "progress",
                    models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
                ),
                ("is_started", models.BooleanField(default=False)),
                ("is_completed", models.BooleanField(default=False)),
                ("valid_till", models.DateField()),
                ("last_accessed_on", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="created_by_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enrolled_to",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "playground",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="learning.playground"),
                ),
            ],
            options={
                "abstract": False,
                "default_related_name": "related_user_playground_trackers",
            },
        ),
        migrations.CreateModel(
            name="PlaygroundGroupTrackingModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ("ss_id", models.IntegerField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("actionee_id", models.PositiveIntegerField(blank=True, default=None, null=True)),
                ("actionee_name", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("reason", models.TextField(blank=True, default=None, null=True)),
                ("action_date", models.DateField(blank=True, default=None, null=True)),
                (
                    "action",
                    models.CharField(
                        choices=[("approved", "Approved"), ("rejected", "Rejected"), ("pending", "Pending")],
                        default="pending",
                        max_length=512,
                    ),
                ),
                ("is_super_admin_approval", models.BooleanField(default=False)),
                ("is_tenant_admin_approval", models.BooleanField(default=False)),
                ("is_self_enrolled", models.BooleanField(default=False)),
                (
                    "progress",
                    models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
                ),
                ("is_started", models.BooleanField(default=False)),
                ("is_completed", models.BooleanField(default=False)),
                ("valid_till", models.DateField()),
                ("last_accessed_on", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="created_by_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enrolled_to",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "playground_group",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="learning.playgroundgroup"),
                ),
            ],
            options={
                "abstract": False,
                "default_related_name": "related_user_playground_group_trackers",
            },
        ),
        migrations.CreateModel(
            name="LearningPathTrackingModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ("ss_id", models.IntegerField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("actionee_id", models.PositiveIntegerField(blank=True, default=None, null=True)),
                ("actionee_name", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("reason", models.TextField(blank=True, default=None, null=True)),
                ("action_date", models.DateField(blank=True, default=None, null=True)),
                (
                    "action",
                    models.CharField(
                        choices=[("approved", "Approved"), ("rejected", "Rejected"), ("pending", "Pending")],
                        default="pending",
                        max_length=512,
                    ),
                ),
                ("is_super_admin_approval", models.BooleanField(default=False)),
                ("is_tenant_admin_approval", models.BooleanField(default=False)),
                ("is_self_enrolled", models.BooleanField(default=False)),
                (
                    "progress",
                    models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
                ),
                ("is_started", models.BooleanField(default=False)),
                ("is_completed", models.BooleanField(default=False)),
                ("valid_till", models.DateField()),
                ("last_accessed_on", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="created_by_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enrolled_to",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "learning_path",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="learning.learningpath"),
                ),
            ],
            options={
                "abstract": False,
                "default_related_name": "related_user_learning_path_trackers",
            },
        ),
        migrations.CreateModel(
            name="ALPTrackingModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ("ss_id", models.IntegerField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("actionee_id", models.PositiveIntegerField(blank=True, default=None, null=True)),
                ("actionee_name", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("reason", models.TextField(blank=True, default=None, null=True)),
                ("action_date", models.DateField(blank=True, default=None, null=True)),
                (
                    "action",
                    models.CharField(
                        choices=[("approved", "Approved"), ("rejected", "Rejected"), ("pending", "Pending")],
                        default="pending",
                        max_length=512,
                    ),
                ),
                ("is_super_admin_approval", models.BooleanField(default=False)),
                ("is_tenant_admin_approval", models.BooleanField(default=False)),
                ("is_self_enrolled", models.BooleanField(default=False)),
                (
                    "progress",
                    models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
                ),
                ("is_started", models.BooleanField(default=False)),
                ("is_completed", models.BooleanField(default=False)),
                ("valid_till", models.DateField()),
                ("last_accessed_on", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "advanced_learning_path",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="learning.advancedlearningpath"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="created_by_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enrolled_to",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_related_name": "related_user_alp_trackers",
            },
        ),
    ]
