# Generated by Django 4.2.3 on 2023-11-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_learning", "0002_enrollment"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="is_enrolled",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="end_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="start_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
