# Generated by Django 4.2.3 on 2023-11-07 21:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("learning", "0003_delete_userfavourite"),
        ("my_learning", "0005_coursemoduletracker_coursesubmoduletracker_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ALPTrackingModel",
            new_name="UserALPTracker",
        ),
        migrations.RenameModel(
            old_name="LearningPathTrackingModel",
            new_name="UserLearningPathTracker",
        ),
        migrations.RenameModel(
            old_name="PlaygroundGroupTrackingModel",
            new_name="UserPlaygroundGroupTracker",
        ),
        migrations.RenameModel(
            old_name="PlaygroundTrackingModel",
            new_name="UserPlaygroundTracker",
        ),
        migrations.RenameModel(
            old_name="SkillTravellerTrackingModel",
            new_name="UserSkillTravellerTracker",
        ),
    ]
