# Generated by Django 4.2.3 on 2023-11-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_learning", "0006_rename_alptrackingmodel_useralptracker_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursemoduletracker",
            name="completion_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="coursemoduletracker",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="coursesubmoduletracker",
            name="completion_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="coursesubmoduletracker",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subroletrackingmodel",
            name="completion_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="subroletrackingmodel",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subskilltrackingmodel",
            name="completion_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="subskilltrackingmodel",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="useralptracker",
            name="completion_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="useralptracker",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usercoursetracker",
            name="completion_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="usercoursetracker",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userlearningpathtracker",
            name="completion_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="userlearningpathtracker",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userplaygroundgrouptracker",
            name="completion_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="userplaygroundgrouptracker",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userplaygroundtracker",
            name="completion_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="userplaygroundtracker",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userskilltravellertracker",
            name="completion_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="userskilltravellertracker",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
