# Generated by Django 4.2.3 on 2023-11-08 13:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("my_learning", "0007_coursemoduletracker_completion_date_and_more"),
        ("my_learning", "0007_remove_usercoursebookmark_created_by_and_more"),
    ]

    operations = []
