# Generated by Django 4.2.3 on 2023-11-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_learning", "0008_merge_20231108_1844"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subskilltrackingmodel",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="subskilltrackingmodel",
            name="enrollment",
        ),
        migrations.RemoveField(
            model_name="subskilltrackingmodel",
            name="modified_by",
        ),
        migrations.RemoveField(
            model_name="subskilltrackingmodel",
            name="sub_skill",
        ),
        migrations.RemoveField(
            model_name="subskilltrackingmodel",
            name="user",
        ),
        migrations.RemoveField(
            model_name="enrollment",
            name="sub_role",
        ),
        migrations.RemoveField(
            model_name="enrollment",
            name="sub_skill",
        ),
        migrations.RemoveField(
            model_name="userfavourite",
            name="sub_role",
        ),
        migrations.RemoveField(
            model_name="userfavourite",
            name="sub_skill",
        ),
        migrations.RemoveField(
            model_name="userrating",
            name="sub_role",
        ),
        migrations.RemoveField(
            model_name="userrating",
            name="sub_skill",
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="learning_type",
            field=models.CharField(
                choices=[
                    ("course", "Course"),
                    ("learning_path", "Learning Path"),
                    ("advanced_learning_path", "Advanced Learning Path"),
                    ("skill_traveller", "Skill Traveller"),
                    ("playground", "Playground"),
                    ("playground_group", "Playground Group"),
                ],
                max_length=512,
            ),
        ),
        migrations.AlterField(
            model_name="userfavourite",
            name="favourite_type",
            field=models.CharField(
                choices=[
                    ("course", "Course"),
                    ("learning_path", "Learning Path"),
                    ("advanced_learning_path", "Advanced Learning Path"),
                    ("skill_traveller", "Skill Traveller"),
                    ("playground", "Playground"),
                    ("playground_group", "Playground Group"),
                    ("category", "Category"),
                    ("skill", "Skill"),
                    ("role", "Role"),
                ],
                max_length=512,
            ),
        ),
        migrations.AlterField(
            model_name="userrating",
            name="learning_type",
            field=models.CharField(
                choices=[
                    ("course", "Course"),
                    ("learning_path", "Learning Path"),
                    ("advanced_learning_path", "Advanced Learning Path"),
                    ("skill_traveller", "Skill Traveller"),
                    ("playground", "Playground"),
                    ("playground_group", "Playground Group"),
                ],
                max_length=512,
            ),
        ),
        migrations.DeleteModel(
            name="SubRoleTrackingModel",
        ),
        migrations.DeleteModel(
            name="SubSkillTrackingModel",
        ),
    ]
