# Generated by Django 4.2.3 on 2023-11-14 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("my_learning", "0009_remove_subskilltrackingmodel_created_by_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coursemoduletracker",
            old_name="parent_tracker",
            new_name="course_tracker",
        ),
        migrations.RenameField(
            model_name="coursesubmoduletracker",
            old_name="parent_tracker",
            new_name="module_tracker",
        ),
        migrations.RemoveField(
            model_name="usercoursebookmark",
            name="sub_module",
        ),
        migrations.AddField(
            model_name="usercoursebookmark",
            name="sub_module_tracker",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="my_learning.coursesubmoduletracker",
            ),
        ),
    ]
