# Generated by Django 4.2.3 on 2023-11-25 15:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("my_learning", "0011_submissionfile_remove_enrollment_actionee_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentsubmission",
            name="is_pass",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="AssignmentYakshaSchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ("ss_id", models.IntegerField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("scheduled_id", models.IntegerField(unique=True)),
                ("scheduled_link", models.URLField()),
                (
                    "assignment_tracker",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="my_learning.assignmenttracker"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "default_related_name": "related_assignment_yaksha_schedules",
            },
        ),
        migrations.CreateModel(
            name="AssignmentYakshaResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ("ss_id", models.IntegerField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("attempt", models.IntegerField()),
                ("duration", models.IntegerField()),
                ("total_questions", models.IntegerField()),
                ("answered", models.IntegerField()),
                ("progress", models.FloatField()),
                ("start_time", models.DateTimeField(blank=True, default=None, null=True)),
                ("end_time", models.DateTimeField(blank=True, default=None, null=True)),
                ("is_pass", models.BooleanField()),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="my_learning.assignmentyakshaschedule"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "default_related_name": "related_assignment_yaksha_results",
            },
        ),
    ]
