# Generated by Django 4.2.3 on 2023-12-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_learning", "0013_rename_attempts_assignmenttracker_allowed_attempt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentsubmission",
            name="is_reviewed",
            field=models.BooleanField(default=False),
        ),
    ]
