# Generated by Django 4.2.3 on 2023-12-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_learning", "0014_assignmentsubmission_is_reviewed"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentsubmission",
            name="pass_percentage",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
