# Generated by Django 4.2.3 on 2023-12-18 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0008_feedbacktemplate_feedbacktemplatequestion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_learning', '0017_lpassessmenttracker_lpayakshaschedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('ss_id', models.IntegerField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True, default=None, null=True)),
                ('choice', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meta.feedbacktemplatechoice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meta.feedbacktemplatequestion')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meta.feedbacktemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'default_related_name': 'related_feedback_responses',
            },
        ),
    ]
