# Generated by Django 4.2.3 on 2024-01-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_learning", "0020_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="name",
            field=models.CharField(default="report", max_length=512),
            preserve_default=False,
        ),
    ]
