# Generated by Django 4.2.3 on 2024-01-19 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("my_learning", "0021_report_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubModuleFileSubmission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True)),
                ("ss_id", models.IntegerField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(blank=True, default=None, null=True)),
                ("feedback", models.TextField(blank=True, default=None, null=True)),
                ("attempt", models.PositiveIntegerField()),
                ("pass_percentage", models.PositiveIntegerField(default=0)),
                ("progress", models.FloatField(default=0)),
                ("is_pass", models.BooleanField(default=False)),
                ("is_reviewed", models.BooleanField(default=False)),
                (
                    "evaluator",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("files", models.ManyToManyField(to="my_learning.submissionfile")),
                (
                    "sub_module_tracker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="my_learning.coursesubmoduletracker"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "default_related_name": "related_sub_module_submissions",
            },
        ),
    ]
