# Generated by Django 4.2.3 on 2024-01-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_learning", "0022_submodulefilesubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentyakshaschedule",
            name="wecp_invite_id",
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="cayakshaschedule",
            name="wecp_invite_id",
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="lpayakshaschedule",
            name="wecp_invite_id",
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
    ]
