# Generated by Django 4.2.3 on 2024-02-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_learning", "0024_alter_report_end_date_alter_report_start_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedbackresponse",
            name="template",
        ),
        migrations.AddField(
            model_name="coursesubmoduletracker",
            name="available_attempt",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="feedbackresponse",
            name="learning_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("course", "Course"),
                    ("learning_path", "Learning Path"),
                    ("advanced_learning_path", "Advanced Learning Path"),
                    ("skill_traveller", "Skill Traveller"),
                    ("playground", "Playground"),
                    ("playground_group", "Playground Group"),
                    ("assignment", "Assignment"),
                ],
                default=None,
                max_length=512,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="feedbackresponse",
            name="learning_type_id",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
