# Generated by Django 4.2.3 on 2024-02-16 10:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("my_learning", "0025_remove_feedbackresponse_template_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="courseassessmenttracker",
            old_name="course_assessment",
            new_name="assessment",
        ),
        migrations.RenameField(
            model_name="lpassessmenttracker",
            old_name="lp_assessment",
            new_name="assessment",
        ),
    ]
