# Generated by Django 4.2.3 on 2024-04-26 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("meta", "0013_mmlconfiguration_assignment_group_and_more"),
        ("my_learning", "0031_enrollment_skill_ontology_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedbackresponse",
            name="choice_ccms_id",
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="feedbackresponse",
            name="is_ccms_obj",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="feedbackresponse",
            name="question_ccms_id",
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="feedbackresponse",
            name="template_ccms_id",
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="feedbackresponse",
            name="learning_type_id",
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="feedbackresponse",
            name="question",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="meta.feedbacktemplatequestion",
            ),
        ),
    ]
