# Generated by Django 4.2.3 on 2024-05-08 12:41

import apps.common.helpers
import apps.common.model_fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("my_learning", "0032_feedbackresponse_choice_ccms_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnouncementImageModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True)),
                ("ss_id", models.IntegerField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    apps.common.model_fields.AppImageField(
                        max_length=512, max_size=5, upload_to=apps.common.helpers.file_upload_path
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="announcement",
            name="title",
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="announcement",
            name="announcement_image",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="my_learning.announcementimagemodel",
            ),
        ),
    ]
