# Generated by Django 4.2.3 on 2023-11-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leaderboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="milestone",
            name="name",
            field=models.CharField(
                choices=[
                    ("first_course_enroll", "First Course Enrolment"),
                    ("first_course_complete", "First Course Completion"),
                    ("first_learning_path_enroll", "First Learning Path Enrolment"),
                    ("first_learning_path_complete", "First Learning Path Completion"),
                    ("course_self_enroll", "Course Self Enrolled"),
                    ("course_assigned", "Course Assigned"),
                    ("learning_path_self_enroll", "Learning Path Self Enrolled"),
                    ("learning_path_assigned", "Learning Path Assigned"),
                    ("upload_profile_picture", "Upload Profile Picture"),
                    ("first_login", "First Login"),
                    ("module_completion_in_first_enrolled_course", "Module Completion In First Enrolled Course"),
                    ("replying_comments", "Replying Comments"),
                ],
                max_length=512,
                unique=True,
            ),
        ),
    ]
