# Generated by Django 4.2.3 on 2023-11-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leaderboard", "0003_alter_milestone_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaderboardactivity",
            name="points",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
