# Generated by Django 4.2.3 on 2024-01-24 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("leaderboard", "0005_alter_leaderboardactivity_uuid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True)),
                ("ss_id", models.IntegerField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[("video", "Video"), ("mml", "MML"), ("assessment", "Assessment")], max_length=512
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("silver", "Silver"), ("gold", "Gold"), ("platinum", "Platinum"), ("video", "Video")],
                        max_length=512,
                    ),
                ),
                (
                    "proficiency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("basic", "Basic"),
                            ("intermediate", "Intermediate"),
                            ("advance", "Advance"),
                            ("comprehensive", "Comprehensive"),
                            ("certification", "Certification"),
                        ],
                        default=None,
                        max_length=512,
                        null=True,
                    ),
                ),
                ("points", models.PositiveIntegerField(blank=True, default=None, null=True)),
                ("from_range", models.PositiveIntegerField(blank=True, default=None, null=True)),
                ("to_range", models.PositiveIntegerField(blank=True, default=None, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="created_by_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="deleted_by_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="modified_by_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_related_name": "related_badges",
            },
        ),
        migrations.CreateModel(
            name="BadgeActivity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True)),
                ("ss_id", models.IntegerField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "learning_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("course", "Course"),
                            ("learning_path", "Learning Path"),
                            ("advanced_learning_path", "Advanced Learning Path"),
                        ],
                        default=None,
                        max_length=512,
                        null=True,
                    ),
                ),
                ("learning_id", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("points", models.PositiveIntegerField(default=0)),
                ("data", models.JSONField(default=dict)),
                ("is_ccms_obj", models.BooleanField(default=False)),
                (
                    "badge",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="leaderboard.badge",
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
                "default_related_name": "related_badge_activities",
            },
        ),
    ]
