# Generated by Django 4.2.3 on 2024-02-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leaderboard", "0006_badge_badgeactivity"),
    ]

    operations = [
        migrations.AddField(
            model_name="badgeactivity",
            name="tracker_id",
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
    ]
