# Generated by Django 4.2.3 on 2024-03-07 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0038_catalogue_is_self_enroll_enabled"),
        ("leaderboard", "0008_alter_milestone_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaderboardactivity",
            name="advanced_learning_path",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="learning.advancedlearningpath",
            ),
        ),
        migrations.AlterField(
            model_name="leaderboardactivity",
            name="course",
            field=models.ForeignKey(
                blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to="learning.course"
            ),
        ),
        migrations.AlterField(
            model_name="leaderboardactivity",
            name="learning_path",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="learning.learningpath",
            ),
        ),
    ]
