# Generated by Django 4.2.3 on 2024-03-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leaderboard", "0009_leaderboardactivity_advanced_learning_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaderboardactivity",
            name="ccms_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="leaderboardactivity",
            name="ccms_id",
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="leaderboardactivity",
            name="is_ccms_obj",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="leaderboardactivity",
            name="learning_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("course", "Course"),
                    ("learning_path", "Learning Path"),
                    ("advanced_learning_path", "Advanced Learning Path"),
                    ("skill_traveller", "Skill Traveller"),
                    ("playground", "Playground"),
                    ("playground_group", "Playground Group"),
                    ("assignment", "Assignment"),
                ],
                default=None,
                max_length=512,
                null=True,
            ),
        ),
    ]
