# Generated by Django 4.2.3 on 2024-03-26 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_alter_forumimagemodel_image_and_more'),
        ('leaderboard', '0011_alter_leaderboardactivity_learning_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardactivity',
            name='forum',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.forum'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='name',
            field=models.CharField(choices=[('first_course_enroll', 'First Course Enrolment'), ('first_course_complete', 'First Course Completion'), ('first_learning_path_enroll', 'First Learning Path Enrolment'), ('first_learning_path_complete', 'First Learning Path Completion'), ('course_self_enroll', 'Course Self Enrolled'), ('course_assigned', 'Course Assigned'), ('learning_path_self_enroll', 'Learning Path Self Enrolled'), ('learning_path_assigned', 'Learning Path Assigned'), ('upload_profile_picture', 'Upload Profile Picture'), ('first_login', 'First Login'), ('module_completion_in_first_enrolled_course', 'Module Completion In First Enrolled Course'), ('forum_post_creation', 'Forum Post Creation'), ('forum_post_comments', 'Forum Post Comments'), ('replying_comments', 'Replying Comments'), ('yaksha_completion', 'Yaksha Completion'), ('yaksha_champion', 'Yaksha Champion'), ('assignment_submission', 'Assignment Submission'), ('assignment_completion', 'Assignment Completion'), ('quick_finisher_self_enrolled_course', 'Quick Finisher Self Enrolled Course'), ('quick_finisher_assigned_course', 'Quick Finisher Assigned Course'), ('quick_finisher_self_enrolled_learning_path', 'Quick Finisher Self Enrolled Learning Path'), ('quick_finisher_assigned_learning_path', 'Quick Finisher Assigned Learning Path'), ('learning_path_starter', 'Learning Path Starter'), ('skill_achiever', 'Skill Achiever'), ('proficiency_achiever', 'Proficiency Achiever'), ('leaderboard_level_promoted', 'Leaderboard Level Promoted'), ('course_certificate_earned', 'Course Certificate Earned'), ('expertise_accomplishment', 'Expertise Accomplishment'), ('following_expert', 'Following Expert'), ('profile_completion', 'Profile Completion'), ('replying_comments_as_expert', 'Replying Comments As Expert'), ('replying_comments_as_expert_ontime', 'Replying Comments As Expert Ontime'), ('forum_creation', 'Forum Creation'), ('learning_path_certificate_earned', 'Learning Path Certificate Earned'), ('first_certification_path_enrollment', 'First Certification Path Enrollment'), ('first_certification_path_completion', 'First Certification Path Completion'), ('certification_path_self_enrolled', 'Certification Path Self Enrolled'), ('certification_path_assigned', 'Certification Path Assigned'), ('quick_finisher_self_enrolled_certification_path', 'Quick Finisher Self Enrolled Certification Path'), ('quick_finisher_assigned_certification_path', 'Quick Finisher Assigned Certification Path'), ('certification_path_starter', 'Certification Path Starter'), ('certification_path_certificate_earned', 'Certification Path Certificate Earned'), ('yaksha_module_completion', 'Yaksha Module Completion'), ('mml_progress', 'MML Progress'), ('video_module_completion', 'Video Module Completion'), ('assignment_module_completion', 'Assignment Module Completion'), ('virtutor_session_completion', 'Virtutor Session Completion'), ('overtaking_peers', 'Overtaking Peers'), ('certification_path_completion', 'Certification Path Completion'), ('learning_path_completion', 'Learning Path Completion'), ('course_completion', 'Course Completion')], max_length=512, unique=True),
        ),
    ]
