# Generated by Django 4.2.3 on 2023-12-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant_service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="databaserouter",
            name="setup_status",
            field=models.CharField(
                choices=[
                    ("initiated", "Initiated"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="initiated",
                max_length=512,
            ),
        ),
    ]
