# Generated by Django 4.2.3 on 2023-12-28 13:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("tenant_service", "0002_databaserouter_setup_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="databaserouter",
            name="uuid",
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True),
        ),
    ]
