# Generated by Django 4.2.3 on 2023-11-22 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("access_control", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="policy",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="policy",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="policy",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="policy",
            name="is_creatable",
        ),
        migrations.RemoveField(
            model_name="policy",
            name="is_deletable",
        ),
        migrations.RemoveField(
            model_name="policy",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="policy",
            name="is_editable",
        ),
        migrations.RemoveField(
            model_name="policy",
            name="is_viewable",
        ),
        migrations.RemoveField(
            model_name="policy",
            name="modified_by",
        ),
        migrations.RemoveField(
            model_name="policycategory",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="policycategory",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="policycategory",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="policycategory",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="policycategory",
            name="modified_by",
        ),
        migrations.RemoveField(
            model_name="userrole",
            name="policies",
        ),
        migrations.AddField(
            model_name="userrole",
            name="role_type",
            field=models.CharField(
                choices=[("admin", "Admin"), ("manager", "Manager"), ("learner", "Learner"), ("author", "Author")],
                default="learner",
                max_length=512,
            ),
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ("ss_id", models.IntegerField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("is_creatable", models.BooleanField(default=False)),
                ("is_viewable", models.BooleanField(default=False)),
                ("is_editable", models.BooleanField(default=False)),
                ("is_deletable", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="created_by_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="deleted_by_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="modified_by_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("policy", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="access_control.policy")),
                ("role", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="access_control.userrole")),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "default_related_name": "related_role_permissions",
            },
        ),
    ]
