# Generated by Django 4.2.3 on 2023-11-27 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("access_control", "0002_remove_policy_created_by_remove_policy_deleted_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usergroup",
            name="manager_email",
        ),
        migrations.AddField(
            model_name="usergroup",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_manager_user_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
