# Generated by Django 4.2.3 on 2023-12-28 13:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("access_control", "0003_remove_usergroup_manager_email_usergroup_manager"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policy",
            name="uuid",
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="policycategory",
            name="uuid",
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="rolepermission",
            name="uuid",
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="usergroup",
            name="uuid",
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="uuid",
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True),
        ),
    ]
