# Generated by Django 4.2.3 on 2023-11-24 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("access_control", "0002_remove_policy_created_by_remove_policy_deleted_at_and_more"),
        ("access", "0003_userfriendrequest_userconnection"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
        migrations.AddField(
            model_name="user",
            name="current_role",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_current_role",
                to="access_control.userrole",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="roles",
            field=models.ManyToManyField(blank=True, related_name="related_user_roles", to="access_control.userrole"),
        ),
    ]
