# Generated by Django 4.2.3 on 2024-03-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("access", "0008_alter_userskilldetail_proficiency"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetail",
            name="certifications",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="userdetail",
            name="promotion_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
