# Generated by Django 4.2.3 on 2024-04-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0009_userdetail_certifications_userdetail_promotion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
    ]
