# Generated by Django 4.2.3 on 2023-12-15 08:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MailTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ("ss_id", models.IntegerField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=512)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("learner_welcome", "Learner Welcome Email"),
                            ("course_completion", "Course Completion"),
                            ("course_self_enrollment", "Course Self-Enrollment"),
                            ("course_admin_assign", "Course Assigned By Admin or Manager"),
                            ("lp_self_enrollment", "LP Self-enrollment"),
                            ("lp_admin_assign", "LP - Admin Assign"),
                            ("alp_self_enrollment", "ALP Self-enrollment"),
                            ("alp_admin_assign", "ALP - Assigned"),
                            ("alp_completion", "ALP - Completion"),
                            ("enrollment_expiration", "Enrollment Expiration"),
                            ("password_reset", "Password Reset"),
                            ("unenrollment", "Unenrollment"),
                            ("bulk_unenrollment", "Bulk Unenrollment"),
                            ("assignment_upload", "Assignment Upload"),
                            ("user_assignment_upload", "User Assignment Upload"),
                            ("user_invite", "User Invite"),
                            ("enrollment_request", "Enrollment Request"),
                            ("scorm_upload", "Scorm Upload"),
                            ("report_trigger", "Report Trigger"),
                            ("assignment_self_enrollment", "Assignment Self-enrollment"),
                            ("assignment_admin_assign", "Assignment - Assigned"),
                            ("certification_mail", "Certification Mail"),
                        ],
                        max_length=512,
                    ),
                ),
                ("subject", models.CharField(max_length=512)),
                ("content", models.TextField()),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "default_related_name": "related_mail_templates",
            },
        ),
    ]
