# Generated by Django 4.2.3 on 2024-05-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailcraft", "0002_alter_mailtemplate_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailtemplate",
            name="type",
            field=models.CharField(
                choices=[
                    ("learner_welcome", "Learner Welcome Email"),
                    ("course_completion", "Course Completion"),
                    ("course_self_enrollment", "Course Self-Enrollment"),
                    ("course_admin_assign", "Course Assigned By Admin or Manager"),
                    ("lp_self_enrollment", "LP Self-enrollment"),
                    ("lp_admin_assign", "LP - Admin Assign"),
                    ("lp_completion", "LP - Completion"),
                    ("alp_self_enrollment", "ALP Self-enrollment"),
                    ("alp_admin_assign", "ALP - Assigned"),
                    ("alp_completion", "ALP - Completion"),
                    ("enrollment_expiration", "Enrollment Expiration"),
                    ("password_reset", "Password Reset"),
                    ("unenrollment", "Unenrollment"),
                    ("bulk_unenrollment", "Bulk Unenrollment"),
                    ("assignment_upload", "Assignment Upload"),
                    ("user_assignment_upload", "User Assignment Upload"),
                    ("user_invite", "User Invite"),
                    ("enrollment_request", "Enrollment Request"),
                    ("scorm_upload", "Scorm Upload"),
                    ("report_trigger", "Report Trigger"),
                    ("assignment_self_enrollment", "Assignment Self-enrollment"),
                    ("assignment_admin_assign", "Assignment - Assigned"),
                    ("certification_mail", "Certification Mail"),
                ],
                max_length=512,
            ),
        ),
    ]
